
project_id = "ehqlkafauehdpqzrdkia"

[functions.kesho-payment]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.send-trending-email]
verify_jwt = false

[functions.send-daily-trending-batch]
verify_jwt = false

[functions.stream-proxy]
verify_jwt = false
